CREATE TABLE servicios (
    id          SERIAL PRIMARY KEY,
    titulo      VARCHAR(200) NOT NULL,
    descripcion TEXT NOT NULL DEFAULT '',
    imagen      VARCHAR(255) NOT NULL DEFAULT '',
    categoria   VARCHAR(50) NOT NULL DEFAULT 'tramites',
    icono       VARCHAR(50) NOT NULL DEFAULT 'document',
    orden       INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO servicios (titulo, descripcion, imagen, categoria, icono, orden) VALUES
('Trámite relacionados a desarrollo urbano','Servicio enfocado en gestionar y dar seguimiento a todos los trámites necesarios ante desarrollo urbano para el desarrollo de un proyecto, asegurando el cumplimiento de normativas urbanas. Incluye permisos, licencias y asesoría técnica para agilizar procesos, reducir riesgos y garantizar la viabilidad del proyecto desde su inicio.','https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80','tramites','document',1),
('Gerencia de Construcción y Director Responsable de Obra (DRO)','Gestoría e Intermediación ante dependencias para permisos de construcción, licencias y regularizaciones.','https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80','tramites','badge',2),
('Gerencia de proyectos','Coordinación en la selección de especialistas y asesores específicos, recomendación para la contratación de empresas contratistas y de servicios, licitación y presentación de propuestas, concursos de obra, revisión de números generadores de obra, estimaciones de obra, escalatorias, reclamos de obra y ajuste de costos.','https://images.unsplash.com/photo-1542621334-a254cf47733d?w=600&q=80','gerencia','users',3),
('Supervisión de Proyectos de construcción en general','Control total de construcción para lograr una correcta ejecución de los proyectos, en cuanto tiempo, costo, seguridad y calidad.','https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80','gerencia','eye',4),
('Diseño y Modelado de proyecto Arquitectónico BIM','Servicio que integra el modelado BIM para desarrollar un proyecto digital preciso y coordinado, junto con la metodología PMI para una gestión eficiente. Permite optimizar tiempos, costos y recursos, reducir errores y asegurar un mejor control durante todo el desarrollo del proyecto.','https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80','diseno','cube',5),
('Dictámenes de uso de suelo','Servicio enfocado en analizar y gestionar el dictamen que define los usos permitidos de un predio. Incluye revisión normativa, trámite ante autoridades y asesoría para asegurar la viabilidad del proyecto y evitar riesgos legales.','https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&q=80','tramites','map',6),
('Dictamen Estructural','Evaluación estructural completa, detección de fallas y riesgos, dictamen técnico profesional y cumplimiento normativo.','https://images.unsplash.com/photo-1565008576549-57569a49371d?w=600&q=80','diseno','structure',7),
('Elaboración de proyectos de áreas verdes para colonias y fraccionamientos','Áreas de descanso, juegos infantiles, pista para caminar, andadores y mobiliario según lo establece el reglamento vigente.','https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=600&q=80','especiales','leaf',8),
('Elaboración de proyectos de sistemas de riego por aspersión automatizada','Proyectos de sistema de riego por aspersión automatizado, el cual consiste en almacenamiento de agua para el riego por aspersión y goteo, elaboramos memoria de cálculo según requerimientos y normas vigentes.','https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80','especiales','water',9),
('Elaboración de proyectos de alumbrado público','Proyectos de alumbrado público en baja tensión en vialidades y áreas verdes, para fraccionamientos y colonias, seleccionando las luminarias más eficientes con tecnología LED, cumpliendo con los requerimientos de alumbrado público, incluye memoria técnica apegándose a la NOM-001 y NOM-013.','https://images.unsplash.com/photo-1515191107209-c28698631303?w=600&q=80','especiales','bulb',10),
('Construcción Residencial','Construcción de casa habitación, remodelación de casa habitación, casa habitación en serie y Residencial.','https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=600&q=80','construccion','home',11),
('Construcción Industrial','Ejecución de obra civil, bodegas, naves industriales, centros comerciales, urbanismo y edificios verticales.','https://images.unsplash.com/photo-1513828583688-c52646db42da?w=600&q=80','construccion','factory',12),
('Consultoría para tu proyecto de construcción','Recabamos la información preliminar disponible de terrenos (normativa, mecánica de suelos, topografía y factibilidades).','https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=80','diseno','chat',13),
('Asesoría en Licitaciones, Ajustes de Costos de obra y Reclamos de Obra','Servicio que brinda apoyo en licitaciones, ajustes de costos y reclamos de obra, asegurando propuestas sólidas, correcta justificación de variaciones y respaldo técnico-contractual, con el objetivo de proteger los intereses económicos de nuestro cliente y reducir riesgos durante el proyecto.','https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80','gerencia','calculator',14);