CREATE TABLE paginas (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    slug VARCHAR(150) UNIQUE NOT NULL,
    contenido TEXT,
    visible BOOLEAN DEFAULT true,
    orden INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);