CREATE TABLE proyectos (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    imagen VARCHAR(255) NOT NULL,
    visible BOOLEAN DEFAULT true,
    orden INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);